#[
abc123
]#

# comment

var export a: Int*, b: Long, c: Byte, l: Int[2], z: Int[2][3]
begin
    var g: Int, d: Int
    a := z[1][1] as Int*
    a := l[0] as Int*
    a := a + (a as Int)
    b := 2l
    d := b as Int
    a := ((b as Int)*2) as Int*
    a := &b as Int*
    g := (b+1l) as Int
    a := ((a as Int)-2-2-2-2+-d) as Int*
    d := (1+2-1)
    c := d2i('3')
    write_eln()
    write_eln
end
